### PR TITLE
Get feedcheck passing + remove sites with expired SSL certs

### PR DESCRIPTION
**Pull request by brettchalupa**
This makes it so `test/feedcheck.rb` passes when we run it, plus you can now check specific sites from the args:

``` console
bundle exec ruby tests/feedcheck.rb santabarbaradsa troydsa
```

### CODE REVIEW

**Comment by brettchalupa** [comment]
I'm gonna make this a draft until the CI checks are passing since that's the ultimate goal of this PR 👍

**Comment by bmos** [comment]
hmm. i wonder why the feed check is failing without listing any failures...

**Comment by brettchalupa** [comment]
@bmos yeah! that's so curious & strange, will investigate 🕵️ 

---

pushed up a commit with the timestamp, here's how it looks:

Screenshot 2024-02-27 at 1 29 39 PM

**Comment by brettchalupa** [comment]
@bmos I figured out the issue, it has to do with excess images, which I think shouldn't cause the test suite to fail, especially with some just commented out. So I'm going to push a commit that makes excess images a WARNING rather than cause failure.

**Comment by brettchalupa** [comment]
@bmos no worries at all! I think I resolved it. ✅

**Comment by brettchalupa** [comment]
@bmos nice! makes more sense now, just pushed up a commit to fix that! I think this is ready for review

**Review by bmos — APPROVED** [review]

**Comment by bmos** [comment]
Your commit [allow passing feed keys to feedcheck test](https://github.com/dsa-ntc/dsa-planet/pull/50/commits/7b279e9ed863c0c1a243dd31397b93c9eabc3a3e) came in really handy when implementing the auto-conversion of new feed issues to pull requests!

**Comment by brettchalupa** [comment]
@bmos so glad to hear that!

**Pull request merged**
